# Generated by Django 3.1.4 on 2021-08-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIM'),
        ),
    ]
