# Generated by Django 3.1.4 on 2021-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profilmahasiswa_nim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilmahasiswa',
            name='nim',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='NIM'),
        ),
    ]
