# Generated by Django 3.1.4 on 2021-08-02 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emodul', '0008_emodul_jumlah_modul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emodulannotation',
            name='dokumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='emodul.emoduldetail', verbose_name='EModul Detail'),
        ),
        migrations.AlterField(
            model_name='emodulbookmark',
            name='dokumen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='emodul.emoduldetail', verbose_name='EModul Detail'),
        ),
        migrations.AlterField(
            model_name='emodulcomment',
            name='dokumen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='emodul.emoduldetail', verbose_name='EModul Detail'),
        ),
        migrations.AlterField(
            model_name='emodulcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna'),
        ),
    ]
