# Generated by Django 3.1.4 on 2021-08-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0011_auto_20210818_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emodul',
            name='penulis',
        ),
        migrations.AddField(
            model_name='emodulannotation',
            name='koordinat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Koordinat'),
        ),
    ]
