# Generated by Django 3.1.4 on 2021-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0012_auto_20210820_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emoduldetail',
            name='file',
            field=models.FileField(upload_to='emodul_detail/%Y/%m/%d/', verbose_name='Berkas'),
        ),
    ]
