# Generated by Django 3.1.4 on 2021-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emodul', '0013_auto_20210822_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='emodul',
            name='cover',
            field=models.ImageField(blank=True, default='images/cover_emodul/default.jpg', null=True, upload_to='images/cover_emodul/', verbose_name='cover'),
        ),
    ]
